CAPTURES = [("normal.pcap", "normal"),
            ("scan.pcap", "scan"),
            ("bruteforce.pcap", "bruteforce"),
            ("dos.pcap", "dos"),
            ("decoy.pcap", "scan"),
            ("normal_web.pcap", "normal"),
            ("normal_stream.pcap", "normal"),
            ("normal_mixed.pcap", "normal"),
            ("scan_syn_lo.pcap", "scan"),
            # ("scan_connect_lo.pcap", "scan"),
            ("scan_slow_router.pcap", "scan"),
            ("scan_connect_router.pcap", "scan"),
            ("decoy2_router.pcap", "scan"),
            ("udp_scan1.pcap", "udp_scan"),
            ("udp_scan2.pcap", "udp_scan"),
            ("normal_dns1.pcap", "normal"),
            ("normal_dns2.pcap", "normal"),
            ("dns_div1.pcap", "normal"),
            ("dns_div2.pcap", "normal"),
            ("dns_div3.pcap", "normal"),
            ("syn_flood1.pcap", "syn_flood"),
            ("syn_flood2.pcap", "syn_flood"),
            # ("dos_t10_lo.pcap", "dos"),
            # ("dos_t40_lo.pcap", "dos"),
            # ("brute_slow_lo.pcap", "bruteforce"),
            # ("brute_fast_lo.pcap", "bruteforce"),]
]